// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paillier.proto

#include "paillier.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace safeheron {
namespace proto {
class PailPubDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PailPub> _instance;
} _PailPub_default_instance_;
class PailPrivDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PailPriv> _instance;
} _PailPriv_default_instance_;
}  // namespace proto
}  // namespace safeheron
static void InitDefaultsPailPub_paillier_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::_PailPub_default_instance_;
    new (ptr) ::safeheron::proto::PailPub();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::safeheron::proto::PailPub::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PailPub_paillier_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPailPub_paillier_2eproto}, {}};

static void InitDefaultsPailPriv_paillier_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::_PailPriv_default_instance_;
    new (ptr) ::safeheron::proto::PailPriv();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::safeheron::proto::PailPriv::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PailPriv_paillier_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPailPriv_paillier_2eproto}, {}};

void InitDefaults_paillier_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_PailPub_paillier_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PailPriv_paillier_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_paillier_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_paillier_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_paillier_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_paillier_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPub, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPub, n_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPub, g_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, n_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, lambda_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, mu_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, p_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, q_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, psqr_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, qsqr_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, pminus1_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, qminus1_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, hp_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, hq_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, qinvp_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, pinvq_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::safeheron::proto::PailPub)},
  { 7, -1, sizeof(::safeheron::proto::PailPriv)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::safeheron::proto::_PailPub_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::safeheron::proto::_PailPriv_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_paillier_2eproto = {
  {}, AddDescriptors_paillier_2eproto, "paillier.proto", schemas,
  file_default_instances, TableStruct_paillier_2eproto::offsets,
  file_level_metadata_paillier_2eproto, 2, file_level_enum_descriptors_paillier_2eproto, file_level_service_descriptors_paillier_2eproto,
};

const char descriptor_table_protodef_paillier_2eproto[] =
  "\n\016paillier.proto\022\017safeheron.proto\"\037\n\007Pai"
  "lPub\022\t\n\001n\030\001 \001(\t\022\t\n\001g\030\002 \001(\t\"\273\001\n\010PailPriv\022"
  "\t\n\001n\030\001 \001(\t\022\016\n\006lambda\030\002 \001(\t\022\n\n\002mu\030\003 \001(\t\022\t"
  "\n\001p\030\004 \001(\t\022\t\n\001q\030\005 \001(\t\022\014\n\004pSqr\030\006 \001(\t\022\014\n\004qS"
  "qr\030\007 \001(\t\022\017\n\007pMinus1\030\010 \001(\t\022\017\n\007qMinus1\030\t \001"
  "(\t\022\n\n\002hp\030\n \001(\t\022\n\n\002hq\030\013 \001(\t\022\r\n\005qInvP\030\014 \001("
  "\t\022\r\n\005pInvQ\030\r \001(\tb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_paillier_2eproto = {
  false, InitDefaults_paillier_2eproto, 
  descriptor_table_protodef_paillier_2eproto,
  "paillier.proto", &assign_descriptors_table_paillier_2eproto, 264,
};

void AddDescriptors_paillier_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_paillier_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_paillier_2eproto = []() { AddDescriptors_paillier_2eproto(); return true; }();
namespace safeheron {
namespace proto {

// ===================================================================

void PailPub::InitAsDefaultInstance() {
}
class PailPub::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PailPub::kNFieldNumber;
const int PailPub::kGFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PailPub::PailPub()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:safeheron.proto.PailPub)
}
PailPub::PailPub(const PailPub& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  n_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.n().size() > 0) {
    n_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.n_);
  }
  g_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.g().size() > 0) {
    g_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.g_);
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.PailPub)
}

void PailPub::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_PailPub_paillier_2eproto.base);
  n_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  g_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

PailPub::~PailPub() {
  // @@protoc_insertion_point(destructor:safeheron.proto.PailPub)
  SharedDtor();
}

void PailPub::SharedDtor() {
  n_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  g_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PailPub::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PailPub& PailPub::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_PailPub_paillier_2eproto.base);
  return *internal_default_instance();
}


void PailPub::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.PailPub)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  n_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  g_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* PailPub::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<PailPub*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string n = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPub.n");
        object = msg->mutable_n();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string g = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPub.g");
        object = msg->mutable_g();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool PailPub::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:safeheron.proto.PailPub)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string n = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_n()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->n().data(), static_cast<int>(this->n().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPub.n"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string g = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_g()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->g().data(), static_cast<int>(this->g().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPub.g"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:safeheron.proto.PailPub)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:safeheron.proto.PailPub)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void PailPub::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:safeheron.proto.PailPub)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->n().data(), static_cast<int>(this->n().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPub.n");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->n(), output);
  }

  // string g = 2;
  if (this->g().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->g().data(), static_cast<int>(this->g().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPub.g");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->g(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:safeheron.proto.PailPub)
}

::google::protobuf::uint8* PailPub::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.PailPub)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->n().data(), static_cast<int>(this->n().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPub.n");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->n(), target);
  }

  // string g = 2;
  if (this->g().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->g().data(), static_cast<int>(this->g().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPub.g");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->g(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.PailPub)
  return target;
}

size_t PailPub::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.PailPub)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->n());
  }

  // string g = 2;
  if (this->g().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->g());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PailPub::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.PailPub)
  GOOGLE_DCHECK_NE(&from, this);
  const PailPub* source =
      ::google::protobuf::DynamicCastToGenerated<PailPub>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.PailPub)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.PailPub)
    MergeFrom(*source);
  }
}

void PailPub::MergeFrom(const PailPub& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.PailPub)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.n().size() > 0) {

    n_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.n_);
  }
  if (from.g().size() > 0) {

    g_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.g_);
  }
}

void PailPub::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.PailPub)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PailPub::CopyFrom(const PailPub& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.PailPub)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PailPub::IsInitialized() const {
  return true;
}

void PailPub::Swap(PailPub* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PailPub::InternalSwap(PailPub* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  n_.Swap(&other->n_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  g_.Swap(&other->g_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata PailPub::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_paillier_2eproto);
  return ::file_level_metadata_paillier_2eproto[kIndexInFileMessages];
}


// ===================================================================

void PailPriv::InitAsDefaultInstance() {
}
class PailPriv::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PailPriv::kNFieldNumber;
const int PailPriv::kLambdaFieldNumber;
const int PailPriv::kMuFieldNumber;
const int PailPriv::kPFieldNumber;
const int PailPriv::kQFieldNumber;
const int PailPriv::kPSqrFieldNumber;
const int PailPriv::kQSqrFieldNumber;
const int PailPriv::kPMinus1FieldNumber;
const int PailPriv::kQMinus1FieldNumber;
const int PailPriv::kHpFieldNumber;
const int PailPriv::kHqFieldNumber;
const int PailPriv::kQInvPFieldNumber;
const int PailPriv::kPInvQFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PailPriv::PailPriv()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:safeheron.proto.PailPriv)
}
PailPriv::PailPriv(const PailPriv& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  n_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.n().size() > 0) {
    n_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.n_);
  }
  lambda_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.lambda().size() > 0) {
    lambda_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lambda_);
  }
  mu_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.mu().size() > 0) {
    mu_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mu_);
  }
  p_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.p().size() > 0) {
    p_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.p_);
  }
  q_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.q().size() > 0) {
    q_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.q_);
  }
  psqr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.psqr().size() > 0) {
    psqr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.psqr_);
  }
  qsqr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.qsqr().size() > 0) {
    qsqr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.qsqr_);
  }
  pminus1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.pminus1().size() > 0) {
    pminus1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pminus1_);
  }
  qminus1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.qminus1().size() > 0) {
    qminus1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.qminus1_);
  }
  hp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hp().size() > 0) {
    hp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hp_);
  }
  hq_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hq().size() > 0) {
    hq_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hq_);
  }
  qinvp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.qinvp().size() > 0) {
    qinvp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.qinvp_);
  }
  pinvq_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.pinvq().size() > 0) {
    pinvq_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pinvq_);
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.PailPriv)
}

void PailPriv::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_PailPriv_paillier_2eproto.base);
  n_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lambda_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mu_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  p_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  q_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  psqr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  qsqr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pminus1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  qminus1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hq_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  qinvp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pinvq_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

PailPriv::~PailPriv() {
  // @@protoc_insertion_point(destructor:safeheron.proto.PailPriv)
  SharedDtor();
}

void PailPriv::SharedDtor() {
  n_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lambda_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mu_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  p_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  q_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  psqr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  qsqr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pminus1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  qminus1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hp_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hq_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  qinvp_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pinvq_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PailPriv::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PailPriv& PailPriv::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_PailPriv_paillier_2eproto.base);
  return *internal_default_instance();
}


void PailPriv::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.PailPriv)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  n_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lambda_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mu_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  p_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  q_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  psqr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  qsqr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pminus1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  qminus1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hq_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  qinvp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pinvq_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* PailPriv::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<PailPriv*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string n = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.n");
        object = msg->mutable_n();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string lambda = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.lambda");
        object = msg->mutable_lambda();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string mu = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.mu");
        object = msg->mutable_mu();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string p = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.p");
        object = msg->mutable_p();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string q = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 42) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.q");
        object = msg->mutable_q();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string pSqr = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 50) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.pSqr");
        object = msg->mutable_psqr();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string qSqr = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 58) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.qSqr");
        object = msg->mutable_qsqr();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string pMinus1 = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 66) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.pMinus1");
        object = msg->mutable_pminus1();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string qMinus1 = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 74) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.qMinus1");
        object = msg->mutable_qminus1();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string hp = 10;
      case 10: {
        if (static_cast<::google::protobuf::uint8>(tag) != 82) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.hp");
        object = msg->mutable_hp();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string hq = 11;
      case 11: {
        if (static_cast<::google::protobuf::uint8>(tag) != 90) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.hq");
        object = msg->mutable_hq();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string qInvP = 12;
      case 12: {
        if (static_cast<::google::protobuf::uint8>(tag) != 98) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.qInvP");
        object = msg->mutable_qinvp();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string pInvQ = 13;
      case 13: {
        if (static_cast<::google::protobuf::uint8>(tag) != 106) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.PailPriv.pInvQ");
        object = msg->mutable_pinvq();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool PailPriv::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:safeheron.proto.PailPriv)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string n = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_n()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->n().data(), static_cast<int>(this->n().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.n"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string lambda = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lambda()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->lambda().data(), static_cast<int>(this->lambda().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.lambda"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string mu = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mu()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->mu().data(), static_cast<int>(this->mu().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.mu"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string p = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_p()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->p().data(), static_cast<int>(this->p().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.p"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string q = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (42 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_q()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->q().data(), static_cast<int>(this->q().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.q"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string pSqr = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (50 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_psqr()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->psqr().data(), static_cast<int>(this->psqr().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.pSqr"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string qSqr = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (58 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_qsqr()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->qsqr().data(), static_cast<int>(this->qsqr().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.qSqr"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string pMinus1 = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (66 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pminus1()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->pminus1().data(), static_cast<int>(this->pminus1().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.pMinus1"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string qMinus1 = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (74 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_qminus1()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->qminus1().data(), static_cast<int>(this->qminus1().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.qMinus1"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string hp = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (82 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hp()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hp().data(), static_cast<int>(this->hp().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.hp"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string hq = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (90 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hq()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hq().data(), static_cast<int>(this->hq().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.hq"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string qInvP = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (98 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_qinvp()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->qinvp().data(), static_cast<int>(this->qinvp().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.qInvP"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string pInvQ = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (106 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pinvq()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->pinvq().data(), static_cast<int>(this->pinvq().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.PailPriv.pInvQ"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:safeheron.proto.PailPriv)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:safeheron.proto.PailPriv)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void PailPriv::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:safeheron.proto.PailPriv)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->n().data(), static_cast<int>(this->n().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.n");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->n(), output);
  }

  // string lambda = 2;
  if (this->lambda().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->lambda().data(), static_cast<int>(this->lambda().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.lambda");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->lambda(), output);
  }

  // string mu = 3;
  if (this->mu().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mu().data(), static_cast<int>(this->mu().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.mu");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->mu(), output);
  }

  // string p = 4;
  if (this->p().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->p().data(), static_cast<int>(this->p().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.p");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->p(), output);
  }

  // string q = 5;
  if (this->q().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->q().data(), static_cast<int>(this->q().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.q");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->q(), output);
  }

  // string pSqr = 6;
  if (this->psqr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->psqr().data(), static_cast<int>(this->psqr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pSqr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->psqr(), output);
  }

  // string qSqr = 7;
  if (this->qsqr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->qsqr().data(), static_cast<int>(this->qsqr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qSqr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->qsqr(), output);
  }

  // string pMinus1 = 8;
  if (this->pminus1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pminus1().data(), static_cast<int>(this->pminus1().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pMinus1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->pminus1(), output);
  }

  // string qMinus1 = 9;
  if (this->qminus1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->qminus1().data(), static_cast<int>(this->qminus1().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qMinus1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->qminus1(), output);
  }

  // string hp = 10;
  if (this->hp().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hp().data(), static_cast<int>(this->hp().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.hp");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->hp(), output);
  }

  // string hq = 11;
  if (this->hq().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hq().data(), static_cast<int>(this->hq().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.hq");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->hq(), output);
  }

  // string qInvP = 12;
  if (this->qinvp().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->qinvp().data(), static_cast<int>(this->qinvp().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qInvP");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->qinvp(), output);
  }

  // string pInvQ = 13;
  if (this->pinvq().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pinvq().data(), static_cast<int>(this->pinvq().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pInvQ");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      13, this->pinvq(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:safeheron.proto.PailPriv)
}

::google::protobuf::uint8* PailPriv::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.PailPriv)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->n().data(), static_cast<int>(this->n().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.n");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->n(), target);
  }

  // string lambda = 2;
  if (this->lambda().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->lambda().data(), static_cast<int>(this->lambda().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.lambda");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->lambda(), target);
  }

  // string mu = 3;
  if (this->mu().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mu().data(), static_cast<int>(this->mu().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.mu");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->mu(), target);
  }

  // string p = 4;
  if (this->p().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->p().data(), static_cast<int>(this->p().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.p");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->p(), target);
  }

  // string q = 5;
  if (this->q().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->q().data(), static_cast<int>(this->q().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.q");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->q(), target);
  }

  // string pSqr = 6;
  if (this->psqr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->psqr().data(), static_cast<int>(this->psqr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pSqr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->psqr(), target);
  }

  // string qSqr = 7;
  if (this->qsqr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->qsqr().data(), static_cast<int>(this->qsqr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qSqr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->qsqr(), target);
  }

  // string pMinus1 = 8;
  if (this->pminus1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pminus1().data(), static_cast<int>(this->pminus1().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pMinus1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->pminus1(), target);
  }

  // string qMinus1 = 9;
  if (this->qminus1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->qminus1().data(), static_cast<int>(this->qminus1().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qMinus1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->qminus1(), target);
  }

  // string hp = 10;
  if (this->hp().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hp().data(), static_cast<int>(this->hp().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.hp");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->hp(), target);
  }

  // string hq = 11;
  if (this->hq().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hq().data(), static_cast<int>(this->hq().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.hq");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->hq(), target);
  }

  // string qInvP = 12;
  if (this->qinvp().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->qinvp().data(), static_cast<int>(this->qinvp().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qInvP");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->qinvp(), target);
  }

  // string pInvQ = 13;
  if (this->pinvq().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pinvq().data(), static_cast<int>(this->pinvq().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pInvQ");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        13, this->pinvq(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.PailPriv)
  return target;
}

size_t PailPriv::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.PailPriv)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->n());
  }

  // string lambda = 2;
  if (this->lambda().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->lambda());
  }

  // string mu = 3;
  if (this->mu().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mu());
  }

  // string p = 4;
  if (this->p().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->p());
  }

  // string q = 5;
  if (this->q().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->q());
  }

  // string pSqr = 6;
  if (this->psqr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->psqr());
  }

  // string qSqr = 7;
  if (this->qsqr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->qsqr());
  }

  // string pMinus1 = 8;
  if (this->pminus1().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pminus1());
  }

  // string qMinus1 = 9;
  if (this->qminus1().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->qminus1());
  }

  // string hp = 10;
  if (this->hp().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hp());
  }

  // string hq = 11;
  if (this->hq().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hq());
  }

  // string qInvP = 12;
  if (this->qinvp().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->qinvp());
  }

  // string pInvQ = 13;
  if (this->pinvq().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pinvq());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PailPriv::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.PailPriv)
  GOOGLE_DCHECK_NE(&from, this);
  const PailPriv* source =
      ::google::protobuf::DynamicCastToGenerated<PailPriv>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.PailPriv)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.PailPriv)
    MergeFrom(*source);
  }
}

void PailPriv::MergeFrom(const PailPriv& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.PailPriv)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.n().size() > 0) {

    n_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.n_);
  }
  if (from.lambda().size() > 0) {

    lambda_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lambda_);
  }
  if (from.mu().size() > 0) {

    mu_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mu_);
  }
  if (from.p().size() > 0) {

    p_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.p_);
  }
  if (from.q().size() > 0) {

    q_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.q_);
  }
  if (from.psqr().size() > 0) {

    psqr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.psqr_);
  }
  if (from.qsqr().size() > 0) {

    qsqr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.qsqr_);
  }
  if (from.pminus1().size() > 0) {

    pminus1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pminus1_);
  }
  if (from.qminus1().size() > 0) {

    qminus1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.qminus1_);
  }
  if (from.hp().size() > 0) {

    hp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hp_);
  }
  if (from.hq().size() > 0) {

    hq_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hq_);
  }
  if (from.qinvp().size() > 0) {

    qinvp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.qinvp_);
  }
  if (from.pinvq().size() > 0) {

    pinvq_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pinvq_);
  }
}

void PailPriv::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.PailPriv)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PailPriv::CopyFrom(const PailPriv& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.PailPriv)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PailPriv::IsInitialized() const {
  return true;
}

void PailPriv::Swap(PailPriv* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PailPriv::InternalSwap(PailPriv* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  n_.Swap(&other->n_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  lambda_.Swap(&other->lambda_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  mu_.Swap(&other->mu_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  p_.Swap(&other->p_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  q_.Swap(&other->q_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  psqr_.Swap(&other->psqr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  qsqr_.Swap(&other->qsqr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  pminus1_.Swap(&other->pminus1_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  qminus1_.Swap(&other->qminus1_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  hp_.Swap(&other->hp_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  hq_.Swap(&other->hq_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  qinvp_.Swap(&other->qinvp_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  pinvq_.Swap(&other->pinvq_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata PailPriv::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_paillier_2eproto);
  return ::file_level_metadata_paillier_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace safeheron
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::safeheron::proto::PailPub* Arena::CreateMaybeMessage< ::safeheron::proto::PailPub >(Arena* arena) {
  return Arena::CreateInternal< ::safeheron::proto::PailPub >(arena);
}
template<> PROTOBUF_NOINLINE ::safeheron::proto::PailPriv* Arena::CreateMaybeMessage< ::safeheron::proto::PailPriv >(Arena* arena) {
  return Arena::CreateInternal< ::safeheron::proto::PailPriv >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
